/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface JsonFile {
  model: string
  hash: string
  content?: Record<string, string>
  embedding: Array<number>
}
export interface ResultItem {
  path: string
  hash: string
  content?: Record<string, string>
  score: number
}
export function computeCosineSimilarity(vector1: Array<number>, vector2: Array<number>): number
export function readJsonAndComputeSimilarity(paths: Array<string>, vert: Array<number>): Array<ResultItem>
